server:
  port: 5555
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka}
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
example:
  property: I AM THE DEFAULT SERVER
# Enable the gateway endpoints to get by example the routes (http://localhost:5555/actuator/gateway/routes/)
management:
  endpoint:
    gateway:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
# Expose gateway endpoints to be consumed in web
  endpoints:
    web:
      exposure:
        include: gateway,health,info
spring:
  cloud:
    gateway:
      routes:
        - id: prefixpath_route
          uri: http://localhost:5555
          filters:
            - PrefixPath=/api
      discovery:
        locator:
          #Enabled create routes based on services registered with a DiscoveryClient
          enabled: true
